_target_: leanspeech.model.Decoder
_partial_: true
drop_path: 0.2
dropout: 0.1
layers:
  - kernel_size: 17
    num_conv_layers: 2
  - kernel_size: 25
    num_conv_layers: 2
  - kernel_size: 9
    num_conv_layers: 2
  - kernel_size: 13
    num_conv_layers: 2
