defaults:
  - _self_
  - encoder: default
  - duration_predictor: default
  - decoder: default
  - optimizer: adamw
  - scheduler: cosine_with_warmup

_target_: leanspeech.model.LeanSpeech
dim: 192
sample_rate: ${data.sample_rate}
n_feats: ${data.n_feats}
loss_weights:
  mel: 5.0
  duration: 1.0
data_statistics: ${data.data_statistics}
