defaults:
  - _self_
  - encoder: default.yaml
  - duration_predictor: default.yaml
  - decoder: default.yaml
  - optimizer: adam.yaml

_target_: leanspeech.model.leanspeech.LeanSpeech
dim: 80
n_vocab: 178
n_feats: 80
data_statistics: ${data.data_statistics}
