defaults:
  - _self_
  - encoder: default.yaml
  - duration_predictor: default.yaml
  - decoder: default.yaml
  - optimizer: adam.yaml
  - scheduler: default.yaml

_target_: leanspeech.model.leanspeech.LeanSpeech
dim: 80
n_vocab: 178
n_feats: 80
loss_weights:
  mel: 10.0
  duration: 1.0
data_statistics: ${data.data_statistics}
